AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t3.micro
        ImageId: <ami-id>
        KeyName: <key-pair-name>
      LaunchTemplateName: !Sub "${AWS::StackName}-LaunchTemplate"
