AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t3.micro
        ImageId: ami-0c55b159cbfafe1f0  # Replace with your region's AMI ID
        KeyName: my-key-pair  # Replace with your key pair name
      LaunchTemplateName: !Sub "${AWS::StackName}-LaunchTemplate"
